
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: root
  password: 123123
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: training_system_development
test:
  <<: *default
  database: training_system_test

production:
  <<: *default
  database: training_system_production
  username: training_system
  password: <%= ENV['TRAINING_SYSTEM_DATABASE_PASSWORD'] %>
